### ISSUE TITLE
Checking for excess iterations in the version without shifts

### ISSUE THREAD

**Issue by Amazingkivas** [Amazingkivas/FDTD_Method#1]
With small partitions, it shows strange results. Nothing critical, but it's better to fix it.

**Comment by gmottajr** [comment]
Shall I help you with that? If yes, please, give me a better context of what need to be changed and where and assign it to me.
Thank you very much!

**Comment by Amazingkivas** [comment]
> Shall I help you with that? If yes, please, give me a better context of what need to be changed and where and assign it to me. Thank you very much!

I will be able to solve this problem myself when I have time, but thank you for your suggestion 🙂
